[tool.poetry]
name = "robotmpcs"
version = "0.1.1"
description = "MPC generation for robots using ForcesPro."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.6,<3.11"
numpy = "^1.15"
casadi = "<=3.5.5"
requests = "^2.27.1"
pyaml = "^21.10.1"
forwardkinematics = {git = "https://git@github.com/maxspahn/forwardKinematics.git", rev = "main"}
planarenvs = {git = "https://git@github.com/maxspahn/gym_envs_planar.git", rev = "master", optional = true}
motion-planning-scenes = {version = "^0.1.0", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
agents = ["planarenvs", "motion-planning-scenes"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
