type: mpc
n: 7
dt: 0.01
H: 15
interval: 10
weights:
  w: 2.5 #speed to goal
  wvel: 0.5 #0.05 #penalize velocity
  ws: 1e-6 #penalize slack
  wu: 0.1 #penalize actions
  wobst: 0.0 #
obst:
  nbObst: 0
slack: False
